name: Deploy project
on: push
jobs: 
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Installing dependencies
              uses: actions/checkout@v4
            - name: Install nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Installing dependencies
          uses: actions/checkout@v4
        - name: Install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm run test
        - name: Build the project
          run: npm run build
        - name: Deploy
          run: echo "Deploying ....."

            
            
                  


    


